### PR TITLE
Compression Headers

### PR DESCRIPTION
**Pull request by gmourier**
# Summary

Compression HTTP headers can be used to improve transfer speed and to reduce bandwidth consumption by sending/receiving compressed, smaller payload.

Send and receive compressed payload, using the `Accept-Encoding` and `Content-Encoding` HTTP headers.

Meilisearch supports `gzip`, `deflate` and `brotli` compression methods.

Related to https://github.com/meilisearch/meilisearch/issues/2802

---

# Changes

- Adds `0178-compression-headers.md` specification file

# Out Of Scope

This specification does not describe the HTTP `Content-Encoding` and `Accept-Encoding` headers. For more information, refer to the related RFCs.

---

# Attention To Reviewers

Describing compression headers in the [open API specification does not seem supported yet](https://github.com/OAI/OpenAPI-Specification/issues/738).

### CODE REVIEW

**Review by curquiza — APPROVED** [review]
I approve for the basics I understood, but I need Kero to firmly validate

**Comment by gmourier** [comment]
The specification details the basics I didn't want to spend time defining `Content-Encoding` and `Accept-Encoding` RFCs 😬 . I hope it's enough for now. 

Feel free to add details that seems important to you @Kerollmops, it will be really appreciated.

**Comment by mou** [comment]
Sorry for interfering, but the specification for `Accept-Encoding` header is more complex. It allows specifying multiple encoding algorithms with the weights corresponding to the order of preference. I believe it is worth leaving at least a [link](https://httpwg.org/specs/rfc9110.html#field.accept-encoding) to it.

**Comment by gmourier** [comment]
Thanks @mou, I will precise that!

**Review by Kerollmops — APPROVED** [review]
That's a short one, and everything looks correct to me 👍

**Pull request merged**
