### PR TITLE
🚧 Search API - Add built-in filter `_geoBoundingBox`

### PR DESCRIPTION
**Pull request by gmourier**
# Summary

- Add the `_geoBoundingBox(({lat}, {lng), {lat}, {lng))` filter expression
- Rewrites the original spec in a long-term format
- Catch up on every missing variant introduced without the spec being kept up to date :rage1: :rage2: :rage3: :rage4: :feelsgood: for `invalid_geo_field`, `invalid_sort` and `invalid_filter` errors

---

# Changes
N/A

# Out Of Scope
N/A

---

# Attention To Reviewers

- Double-check the error variants.

---

## Misc

- [] Update OpenAPI specification file _(if needed; Apply the `OpenApi` label)_
- [] Update telemetry datapoints _(if needed; Apply the `Telemetry` label)_

### CODE REVIEW

**Comment by gmourier** [comment]
@irevoire I think we can start with a fresh new spec because that one is describing older changes that have happened since v1.0 (error description and variants description for geo related errors) WDYT?

**Comment by irevoire** [comment]
Oops, yes, I thought this one was already merged

**Comment by gmourier** [comment]
I'm on it!

**Comment by gmourier** [comment]
Replace by https://github.com/meilisearch/specifications/pull/223

**Pull request closed without merging**
